[package]
name = "twch-cli"
version = "0.1.0"
authors = ["mosm <airman515@gmail.com>"]
edition = "2018"

[[bin]]
name = "twch"
path = "src/main.rs"

[dependencies]
actix-web = "3.3.2"
anyhow = "1.0.40"
dotenv = "0.14.0"
futures = "0.3.15"
structopt = "0.3.21"
twch = { path = ".." }
