[package]
name = "twch-server"
version = "0.1.0"
authors = ["mosm <airman515@gmail.com>"]
edition = "2018"

[dependencies]
actix-web = "3.3.2"
anyhow = "1.0.40"
dotenv = "0.14.0"
env_logger = "0.8.3"
futures = "0.3.15"
serde = { version = "1.0.126", features = ["derive"] }
twch = { path = ".." }
